[WIP] Use API v13 for update Leads
agendor/rdstation-php-client pull request #7
Opened 2017-02-01 19:44 UTC by filipenasc

## Work in progress

2017-02-01 19:50 UTC, filipenasc commented
@brunogianni :up:

2017-02-07 12:09 UTC, tuliomonteazul requested changes
Valeu pela contribuição. Fiz alguns comentários

2017-02-07 12:09 UTC, tuliomonteazul commented on RDStationAPI.class.php
> +    $new_data['lead'] = $data;
Não encontrei aonde essa variável `$new_data` foi declarada. Seria melhor inicializar o array pra evitar warnings.
Também é melhor renomear para `$newData` para seguir a convenção de código do projeto.

2017-02-07 12:09 UTC, tuliomonteazul commented on RDStationAPI.class.php
> +    $data['email'] = $email;
Aqui e em outras mudanças a indentação mudou de tabs para 2 espaços. Eu particularmente prefiro 2 espaços também mas pra não ficar misturado (o que dificulta a leitura) é melhor manter com tabs (ou mudar tudo pra 2 espaços).

2017-02-07 12:09 UTC, tuliomonteazul commented on RDStationAPI.class.php
> +    $url = $this->getURL('leads', '1.3').$email;
Não seria melhor a versão da API `'1.3'` poder ser recebida como parâmetro também?
E não seria melhor o default ser `'1.2'` assim como no método `getURL`?
Sugiro colocar o default em uma constante estática do tipo `API_VERSION`

2017-02-10 16:41 UTC, filipenasc commented on RDStationAPI.class.php
> +    $data['email'] = $email;
Boa! Meu editor faz a indentação com 2 espaços automaticamente e deixei passar despercebido.

2017-02-10 16:43 UTC, filipenasc commented on RDStationAPI.class.php
> +    $data['email'] = $email;
Vou deixar tudo com 2 espaços, o que acha?

2017-02-10 18:19 UTC, tuliomonteazul commented on RDStationAPI.class.php
> +    $data['email'] = $email;
@filipenasc Beleza, 2 espaços fica ótimo!

2017-02-14 17:00 UTC, filipenasc commented on RDStationAPI.class.php
> +    $url = $this->getURL('leads', '1.3').$email;
O problema nesse caso é que algumas funcionalidades só existem na versão 1.2 e outras só na 1.3 :confused:

2017-02-14 17:00 UTC, filipenasc commented on RDStationAPI.class.php
> +    $new_data['lead'] = $data;
Verdade, acabei deixando passar despercebido, vou ajustar esses padrões.

2017-02-14 17:02 UTC, filipenasc commented
Valeu pelo review, @tuliomonteazul . Comecei a revisar as coisas que você citou na semana passada, mas acabei tendo que focar em outra coisa. Essa semana vou tirar um tempo pra fazer esses ajustes :+1:

2017-02-16 11:46 UTC, tuliomonteazul approved these changes

2017-02-16 11:46 UTC, merged

2017-02-16 11:47 UTC, tuliomonteazul commented
Beleza @filipenasc! Tudo certo, valeu pela contribuição 👍